### ISSUE TITLE
سلام 😊

### ISSUE THREAD

**Issue by gh4rib** [Azumi67/udp2raw-core#1]
سلام وقت بخیر
میدونم این کار و مسیر ارتباطی روش درستی نیست و در شان شما و حتی اینجا توی issues نیست،
اما شما هیچ راه ارتباطی مثل ایمیل هم قرار ندادین البته حق هم دارین.
من یکم کدهای شمارو نگاه کردم و کارهایی که میکنین و خیلییی خوشم اومد😍😍 از این همه contribution  موثر شما و البته کدهایی که دولوپ کردین، برام جذاب و unique محسوب میشه میخواستم باهاتون آشنا بشم امیدوارم گستاخی برداشت نشه این رفتارم و پیشاپیش عذر خواهی 
میکنم اگر اینطور بنظرم اومد
میشه بهم خبر بدین هرطور که مایلین

**Comment by Azumi67** [comment]
سلام مرسی. خوشحالم که خوشتون اومده. من راستش وقت زیادی برای کارهای دیگه ندارم و گیت هابم هم مکانیه برام که تمرین کنم و یاد بگیرم.کنارش آموزش هم مینویسم که دیگران استفاده کنن وگرنه هدف من بیشتر تمرینه. من پروفایل شما هم نگاه کردم و خیلی جالب بود. ممنونم از دیدگاهتون
